name: Build and Deploy to GKE

on: 
  push:
    branches: 
    - 'main'

jobs:
  kubernetes:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: authenticating into cluster
        run: |
          gcloud config set project august-shield-345908
          gcloud container clusters get-credentials cluster-1 --region=us-central1-c
  
      - name: setup Helm3
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm plugin install https://github.com/databus23/helm-diff
      
      - name: helm mychart
        run: |
          helm install my-release .
          helm upgrade my-release
